spring.application.name=billkeeper-backend
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:10490/postgres
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true

settings.ocr-enabled=false
settings.tesseract-language=
settings.tesseract-data-directory=

settings.documents-directory=/tmp/uploaded-documents
settings.users-directory=/tmp/users-data
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
settings.server-url=http://localhost:8080
settings.front-url=http://localhost:4200
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:10491/realms/billkeeper

spring.mail.host=localhost
spring.mail.port=10494
spring.mail.username=test@billkeeper.test
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false